# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npath.proto\x12\x06Notice\"\xb7\x02\n\x0cPathResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\x05\x12\x15\n\rcontrol_param\x18\x02 \x01(\x05\x12\x14\n\x0cservice_type\x18\x03 \x01(\x05\x12\x17\n\x0finstance_status\x18\x04 \x01(\x05\x12\x18\n\x10instance_version\x18\x05 \x01(\x05\x12\x1c\n\x14service_dest_address\x18\x06 \x01(\t\x12\x19\n\x11\x63urrent_hop_count\x18\x07 \x01(\x05\x12\x15\n\rmax_hop_count\x18\x08 \x01(\x05\x12\x0b\n\x03ttl\x18\t \x01(\x05\x12\x15\n\rheartbeat_msg\x18\n \x01(\x05\x12\x13\n\x0breturn_port\x18\x0b \x01(\x05\x12\x16\n\x0ereturn_address\x18\x0c \x01(\t\x12\x11\n\textension\x18\r \x01(\x0c\"\x89\x02\n\x0bPathRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\x05\x12\x15\n\rcontrol_param\x18\x02 \x01(\x05\x12\x14\n\x0cservice_type\x18\x03 \x01(\x05\x12\x17\n\x0finstance_status\x18\x04 \x01(\x05\x12\x18\n\x10instance_version\x18\x05 \x01(\x05\x12\x1c\n\x14service_dest_address\x18\x06 \x01(\t\x12\x19\n\x11\x63urrent_hop_count\x18\x07 \x01(\x05\x12\x15\n\rmax_hop_count\x18\x08 \x01(\x05\x12\x0b\n\x03ttl\x18\t \x01(\x05\x12\x15\n\rheartbeat_msg\x18\n \x01(\x05\x12\x11\n\textension\x18\x0b \x01(\x0c\x32<\n\x04Path\x12\x34\n\x05Greet\x12\x13.Notice.PathRequest\x1a\x14.Notice.PathResponse\"\x00\x42\x1a\n\tio.noticeB\x0bNoticeProtoP\x01\x62\x06proto3')



_PATHRESPONSE = DESCRIPTOR.message_types_by_name['PathResponse']
_PATHREQUEST = DESCRIPTOR.message_types_by_name['PathRequest']
PathResponse = _reflection.GeneratedProtocolMessageType('PathResponse', (_message.Message,), {
  'DESCRIPTOR' : _PATHRESPONSE,
  '__module__' : 'path_pb2'
  # @@protoc_insertion_point(class_scope:Notice.PathResponse)
  })
_sym_db.RegisterMessage(PathResponse)

PathRequest = _reflection.GeneratedProtocolMessageType('PathRequest', (_message.Message,), {
  'DESCRIPTOR' : _PATHREQUEST,
  '__module__' : 'path_pb2'
  # @@protoc_insertion_point(class_scope:Notice.PathRequest)
  })
_sym_db.RegisterMessage(PathRequest)

_PATH = DESCRIPTOR.services_by_name['Path']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\tio.noticeB\013NoticeProtoP\001'
  _PATHRESPONSE._serialized_start=23
  _PATHRESPONSE._serialized_end=334
  _PATHREQUEST._serialized_start=337
  _PATHREQUEST._serialized_end=602
  _PATH._serialized_start=604
  _PATH._serialized_end=664
# @@protoc_insertion_point(module_scope)
